name: Action CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: gradle/gradle-build-action@v2
      - name: Retrieve version
        run: |
          echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease